In [3]:
import numpy as np 
import pandas as pd

In [4]:
movies = pd.read_csv('data\movies.csv') 
credits = pd.read_csv('data\credits.csv')

In [5]:
print(movies.dtypes)

budget                    int64
genres                   object
homepage                 object
id                        int64
keywords                 object
original_language        object
original_title           object
overview                 object
popularity              float64
production_companies     object
production_countries     object
release_date             object
revenue                   int64
runtime                 float64
spoken_languages         object
status                   object
tagline                  object
title                    object
vote_average            float64
vote_count                int64
dtype: object

In [6]:

print(credits.shape)
print(movies.shape)
#print(credits.dtypes)
#print(movies.dtypes)

(4803, 4)
(4803, 20)

In [7]:
display(movies['id'])
display(credits['movie_id'])

0        19995
1          285
2       206647
3        49026
4        49529
         ...
4798      9367
4799     72766
4800    231617
4801    126186
4802     25975
Name: id, Length: 4803, dtype: int64

0        19995
1          285
2       206647
3        49026
4        49529
         ...
4798      9367
4799     72766
4800    231617
4801    126186
4802     25975
Name: movie_id, Length: 4803, dtype: int64

In [8]:
movies_df = movies.merge(credits, left_on='id', right_on='movie_id', how='inner')
print(movies_df.columns)
print(movies_df.shape)

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title_x', 'vote_average',
       'vote_count', 'movie_id', 'title_y', 'cast', 'crew'],
      dtype='object')
(4803, 24)

In [9]:
# Numerical Features (Useful for Recommendation):
# movie_id
# budget 
# revenue
# runtime 
# keywords
# original_title
# popularity
# vote_average
# vote_count

# Categorical/Text Features (Useful for Content-Based Filtering):
# title_x
# genres 
# keywords
# original_language
# overview 
# cast 
# crew

In [10]:
df = movies_df[['genres','movie_id', 'budget', 'revenue', 'runtime', 'keywords', 'original_title', 'popularity', 'vote_average', 'vote_count']]

In [11]:
print(df.shape)
df.info()

(4803, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   genres          4803 non-null   object
 1   movie_id        4803 non-null   int64
 2   budget          4803 non-null   int64
 3   revenue         4803 non-null   int64
 4   runtime         4801 non-null   float64
 5   keywords        4803 non-null   object
 6   original_title  4803 non-null   object
 7   popularity      4803 non-null   float64
 8   vote_average    4803 non-null   float64
 9   vote_count      4803 non-null   int64
dtypes: float64(3), int64(4), object(3)
memory usage: 375.4+ KB

In [12]:
print(df.isnull().sum())
df.dropna(inplace=True)
df.isnull().sum()
print(df.duplicated().sum())

genres            0
movie_id          0
budget            0
revenue           0
runtime           2
keywords          0
original_title    0
popularity        0
vote_average      0
vote_count        0
dtype: int64
0

C:\Users\Himanshu Sharma\AppData\Local\Temp\ipykernel_1856\2939571442.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(inplace=True)

In [13]:
df.head(2)

,genres,movie_id,budget,revenue,runtime,keywords,original_title,popularity,vote_average,vote_count
0,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,237000000,2787965087,162.0,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,150.437577,7.2,11800
1,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,300000000,961000000,169.0,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,139.082615,6.9,4500

In [17]:
df.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [15]:
import ast  # To parse string representations of lists

def convert(text):
    L = []
    for i in ast.literal_eval(text):
        L.append(i['name']) 
    return L

In [ ]:
df['genres'] = df['genres'].apply(convert)
df.head()

,genres,movie_id,budget,revenue,runtime,keywords,original_title,popularity,vote_average,vote_count
0,"[Action, Adventure, Fantasy, Science Fiction]",19995,237000000,2787965087,162.0,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,150.437577,7.2,11800
1,"[Adventure, Fantasy, Action]",285,300000000,961000000,169.0,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,139.082615,6.9,4500
2,"[Action, Adventure, Crime]",206647,245000000,880674609,148.0,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,107.376788,6.3,4466
3,"[Action, Crime, Drama, Thriller]",49026,250000000,1084939099,165.0,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,112.312950,7.6,9106
4,"[Action, Adventure, Science Fiction]",49529,260000000,284139100,132.0,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,43.926995,6.1,2124

In [ ]:
df['keywords'] = df['keywords'].apply(convert)
df['cast'] = df['cast'].apply(convert)
df['crew'] = df['crew'].apply(convert)

ValueError: malformed node or string: ['culture clash', 'future', 'space war', 'space colony', 'society', 'space travel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alien planet', 'cgi', 'marine', 'soldier', 'battle', 'love affair', 'anti war', 'power relations', 'mind and soul', '3d']